API_NAME : "OPENROUTER_API_KEY"
MODEL_NAME_2 : "deepseek/deepseek-chat-v3-base:free"
MODEL_NAME : "deepseek/deepseek-chat-v3-0324:free"
DEFAULT_SYSTEM_PROMPT_PATH : "system_prompt.txt"
MAX_INPUT_LENGTH : 20000