name: Continuous Deployment to Vercel

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  cd:
    name: Trigger Vercel Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Staging
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'staging' && success()
        run: curl -X POST ${{ secrets.STAGING }}

      - name: Deploy to Production
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && success()
        run: curl -X POST ${{ secrets.PRODUCTION }}