name: Continuous Deployment to Vercel

on:
  push:
    branches: [ main, pre-production ]

jobs:
  cd:
    name: Trigger Vercel Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Pre-Production
        if: github.ref == 'refs/heads/pre-production'
        run: curl -X POST ${{ secrets.PRE_PRODUCTION }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: curl -X POST ${{ secrets.PRODUCTION }}