name: Performance Benchmarks 

on:
  workflow_dispatch:  # Manual trigger only (no auto-run)

jobs:
  run-benchmarks:
    name: Check Performance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> $GITHUB_ENV
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
          echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> $GITHUB_ENV

    - name: Run Benchmark Script
      env:
        TOKENIZERS_PARALLELISM: "false"
      run: |
        PYTHONPATH=. python benchmarks/check_performance.py
    
    - name: Upload Resume Extractor Performance Metrics JSON
      uses: actions/upload-artifact@v4
      with:
        name: Resume-Extractor-Performance-Metrics
        path: benchmarks/results/resume_extractor_performance.json

    - name: Upload JD Extractor Performance Metrics JSON
      uses: actions/upload-artifact@v4
      with:
        name: JD-Extractor-Performance-Metrics
        path: benchmarks/results/jd_extractor_performance.json

    - name: Upload Matchmaker Performance Metrics JSON
      uses: actions/upload-artifact@v4
      with:
        name: Matchmaker-Performance-Metrics
        path: benchmarks/results/matchmaker_performance.json
    
    - name: Upload Performance Report CSV
      uses: actions/upload-artifact@v4
      with:
        name: Performance-Report
        path: benchmarks/results/performance_report.csv

