name: Python Tests and Coverage (Unit + Integration + API)

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set environment variables
      run: |
        echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> $GITHUB_ENV
        echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> $GITHUB_ENV
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
        echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y poppler-utils tesseract-ocr

    - name: Run Unit Tests Only
      run: |
        COVERAGE_FILE=.coverage.unit PYTHONPATH=. pytest --cov=src --cov=api --cov=db --cov-report=term-missing --cov-report=html -m "unit" tests/
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: unit-coverage-report
        path: htmlcov/
    
    - name: Upload Unit Test Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: .coverage.unit
        flags: unit
        fail_ci_if_error: false

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'staging'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      
    - name: Set environment variables
      run: |
        echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> $GITHUB_ENV
        echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> $GITHUB_ENV
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
        echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y poppler-utils tesseract-ocr

    - name: Run Integration Tests
      run: |
        COVERAGE_FILE=.coverage.integration PYTHONPATH=. pytest --cov=src --cov=api --cov=db --cov-report=term-missing --cov-report=html -m "integration" tests/

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: integration-coverage-report
        path: htmlcov/

    - name: Upload Integration Test Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: .coverage.integration
        flags: integration
        fail_ci_if_error: false
  
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'staging'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      
    - name: Set environment variables
      run: |
        echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> $GITHUB_ENV
        echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> $GITHUB_ENV
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
        echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y poppler-utils tesseract-ocr

    - name: Run API Tests
      run: |
        COVERAGE_FILE=.coverage.api PYTHONPATH=. pytest --cov=src --cov=api --cov=db --cov-report=term-missing --cov-report=html -m "api" tests/ 

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: api-coverage-report
        path: htmlcov/

    - name: Upload API Test Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: .coverage.api
        flags: api
        fail_ci_if_error: false