name: Python Tests and Coverage (Unit + Integration)

on:
  push:
    branches: [ main, feature/**, bugfix/** ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set environment variables
      run: echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt

    - name: Run Unit Tests Only
      run: |
        PYTHONPATH=. pytest --cov=src --cov-report=term-missing --cov-report=html -m "unit" tests/

    - name: Save Unit Test Coverage File
      run: |
        mv .coverage .coverage.unit
    
    - name: Upload Unit Coverage File
      uses: actions/upload-artifact@v4
      with:
        name: unit-coverage
        path: .coverage.unit

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests 

    # if: github.ref == 'refs/heads/main' 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      
    - name: Set environment variables
      run: echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt

    - name: Run Integration Tests
      run: |
        PYTHONPATH=. pytest --cov=src --cov-report=term-missing --cov-report=html -m "integration" tests/

    - name: Save Integration Test Coverage File
      run: |
        mv .coverage .coverage.integration

    - name: Upload Integration Coverage File
      uses: actions/upload-artifact@v4
      with:
        name: integration-coverage
        path: .coverage.integration

  combine-coverage:
    name: Combine Coverage Reports
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Unit Coverage
      uses: actions/download-artifact@v4
      with:
        name: unit-coverage
        path: coverage-temp/

    - name: Download Integration Coverage
      uses: actions/download-artifact@v4
      with:
        name: integration-coverage
        path: coverage-temp/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage[toml]

    - name: Combine Coverage Files and Generate Report
      run: |
        coverage combine coverage-temp/.coverage.unit coverage-temp/.coverage.integration
        coverage html -d htmlcov/

    - name: Upload Combined Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: combined-coverage-report
        path: htmlcov/

    - name: Upload combined coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true